import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        {
            bookingReference: 'BK-20241210-001',
            userId: 2,
            vehicleId: 1,
            pickupDate: new Date('2024-12-17').toISOString(),
            returnDate: new Date('2024-12-20').toISOString(),
            pickupTime: '10:00',
            returnTime: '18:00',
            pickupAddress: 'Bandra West, Mumbai, Maharashtra 400050',
            dropoffAddress: 'Andheri East, Mumbai, Maharashtra 400069',
            driverName: 'Rajesh Kumar',
            driverPhone: '+91 9876543210',
            driverEmail: 'rajesh.kumar@driverservice.com',
            extrasInsurance: true,
            extrasDriver: false,
            extrasChildSeat: true,
            promoCode: null,
            basePrice: '6000',
            extrasPrice: '500',
            taxes: '1170',
            totalAmount: '7670',
            paymentMethod: 'full',
            status: 'confirmed',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            bookingReference: 'BK-20241209-002',
            userId: 3,
            vehicleId: 3,
            pickupDate: new Date('2024-12-09').toISOString(),
            returnDate: new Date('2024-12-12').toISOString(),
            pickupTime: '09:00',
            returnTime: '20:00',
            pickupAddress: 'Powai, Mumbai, Maharashtra 400076',
            dropoffAddress: 'Worli, Mumbai, Maharashtra 400018',
            driverName: 'Amit Sharma',
            driverPhone: '+91 9123456789',
            driverEmail: 'amit.sharma@driverservice.com',
            extrasInsurance: true,
            extrasDriver: true,
            extrasChildSeat: false,
            promoCode: 'SAVE10',
            basePrice: '10800',
            extrasPrice: '1500',
            taxes: '2214',
            totalAmount: '14514',
            paymentMethod: 'deposit',
            status: 'active',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            bookingReference: 'BK-20241125-003',
            userId: 4,
            vehicleId: 2,
            pickupDate: new Date('2024-11-26').toISOString(),
            returnDate: new Date('2024-11-30').toISOString(),
            pickupTime: '08:30',
            returnTime: '19:30',
            pickupAddress: 'Malad West, Mumbai, Maharashtra 400064',
            dropoffAddress: 'Thane West, Mumbai, Maharashtra 400601',
            driverName: 'Suresh Patil',
            driverPhone: '+91 9988776655',
            driverEmail: 'suresh.patil@driverservice.com',
            extrasInsurance: false,
            extrasDriver: false,
            extrasChildSeat: false,
            promoCode: null,
            basePrice: '4576',
            extrasPrice: '0',
            taxes: '824',
            totalAmount: '5400',
            paymentMethod: 'full',
            status: 'completed',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-30').toISOString(),
        },
        {
            bookingReference: 'BK-20241208-004',
            userId: 2,
            vehicleId: 5,
            pickupDate: new Date('2025-01-15').toISOString(),
            returnDate: new Date('2025-01-18').toISOString(),
            pickupTime: '11:00',
            returnTime: '17:00',
            pickupAddress: 'Colaba, Mumbai, Maharashtra 400005',
            dropoffAddress: 'Marine Drive, Mumbai, Maharashtra 400020',
            driverName: 'Vikram Singh',
            driverPhone: '+91 9234567890',
            driverEmail: 'vikram.singh@driverservice.com',
            extrasInsurance: true,
            extrasDriver: true,
            extrasChildSeat: true,
            promoCode: 'PREMIUM20',
            basePrice: '20340',
            extrasPrice: '2000',
            taxes: '4021',
            totalAmount: '26361',
            paymentMethod: 'deposit',
            status: 'pending',
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            bookingReference: 'BK-20241202-005',
            userId: 3,
            vehicleId: 7,
            pickupDate: new Date('2024-12-03').toISOString(),
            returnDate: new Date('2024-12-05').toISOString(),
            pickupTime: '14:00',
            returnTime: '16:00',
            pickupAddress: 'Juhu, Mumbai, Maharashtra 400049',
            dropoffAddress: 'Versova, Mumbai, Maharashtra 400061',
            driverName: 'Mahesh Joshi',
            driverPhone: '+91 9876012345',
            driverEmail: 'mahesh.joshi@driverservice.com',
            extrasInsurance: true,
            extrasDriver: false,
            extrasChildSeat: false,
            promoCode: null,
            basePrice: '5424',
            extrasPrice: '400',
            taxes: '1048',
            totalAmount: '6872',
            paymentMethod: 'full',
            status: 'cancelled',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        }
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});